version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/images:/app/images  # Persist generated images

  frontend:
    build: ./frontend
    ports:
      - "8600:8600"
    depends_on:
      - backend
