version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
